ALTER TABLE "Agency"
  ADD COLUMN IF NOT EXISTS "aiUrgencyThreshold" INTEGER NOT NULL DEFAULT 75,
  ADD COLUMN IF NOT EXISTS "aiMatchingMode" TEXT NOT NULL DEFAULT 'CONSERVADOR',
  ADD COLUMN IF NOT EXISTS "aiOutreachTone" TEXT NOT NULL DEFAULT 'Sofisticado y reservado';
